### ISSUE TITLE
FK filter

### ISSUE THREAD

**Issue by mloubout** [SeismicJulia/SeisProcessing.jl#12]
The FK filter is not working

https://github.com/SeismicJulia/SeisProcessing.jl/blob/31c9f48933caeaa4a33bf9ad5835cae9fafd870c/src/Processing/SeisFKFilter.jl#L51

- `dp` is undefined there.
- `dw` undefined like 55

**Comment by fercarozzi** [comment]
Thanks for the heads up. I just pushed a fix. 
Should work now. Let us know otherwise.

**Comment by mloubout** [comment]
Ok thanks, will check with next release.
BTW the `Manifest.toml` shouldn't be in the package leaving it will break a lot of users environments.

**Comment by fercarozzi** [comment]
Thanks for the suggestion.
For now, we'll leave the Manifest in the repo. This decision was made at
the beginning of julia1 when many packages were being updated, and many
still not. In this way, we knew there was at least one configuration to
follow that should work.
We will:
- evaluate adding a note on the readme file as a warning for general users.
- removing the manifest.toml file from the repo in future releases.
Thanks.
